In [ ]:

import subprocess
import numpy as np
import pandas as pd

In [ ]:
dfUrls = pd.read_csv("urls_to_get.csv")
dfUrls.head()

                                                urls
0  https://s3.amazonaws.com/tripdata/201901-citib...
1  https://s3.amazonaws.com/tripdata/201902-citib...
2  https://s3.amazonaws.com/tripdata/201903-citib...
3  https://s3.amazonaws.com/tripdata/201904-citib...
4  https://s3.amazonaws.com/tripdata/201905-citib...

In [ ]:
for i,row in dfUrls.iterrows():
  print(row['urls'])
  subprocess.run(['wget',row['urls']])
  subprocess.run(['unzip',row['urls'].split("/")[-1]])

https://s3.amazonaws.com/tripdata/201901-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201902-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201903-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201904-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201905-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201906-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201907-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201908-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201909-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201910-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201911-citibike-tripdata.csv.zip
https://s3.amazonaws.com/tripdata/201912-citibike-tripdata.csv.zip

In [ ]:
result = subprocess.run(["ls"],capture_output=True,text=True)
print(result.stdout)

201306-citibike-tripdata.csv
201306-citibike-tripdata.zip
2013-07 - Citi Bike trip data.csv
201307-citibike-tripdata.zip
2013-08 - Citi Bike trip data.csv
201308-citibike-tripdata.zip
2013-09 - Citi Bike trip data.csv
201309-citibike-tripdata.zip
2013-10 - Citi Bike trip data.csv
201310-citibike-tripdata.zip
2013-11 - Citi Bike trip data.csv
201311-citibike-tripdata.zip
2013-12 - Citi Bike trip data.csv
201312-citibike-tripdata.zip
2014-01 - Citi Bike trip data.csv
201401-citibike-tripdata.zip
2014-02 - Citi Bike trip data.csv
201402-citibike-tripdata.zip
2014-03 - Citi Bike trip data.csv
201403-citibike-tripdata.zip
2014-04 - Citi Bike trip data.csv
201404-citibike-tripdata.zip
2014-05 - Citi Bike trip data.csv
201405-citibike-tripdata.zip
2014-06 - Citi Bike trip data.csv
201406-citibike-tripdata.zip
2014-07 - Citi Bike trip data.csv
201407-citibike-tripdata.zip
2014-08 - Citi Bike trip data.csv
201408-citibike-tripdata.zip
201409-citibike-tripdata.csv
201409-citibike-tripdata.zip
201410-citibike-tripdata.csv
201410-citibike-tripdata.zip
201411-citibike-tripdata.csv
201411-citibike-tripdata.zip
201412-citibike-tripdata.csv
201412-citibike-tripdata.zip
201501-citibike-tripdata.csv
201501-citibike-tripdata.zip
201502-citibike-tripdata.csv
201502-citibike-tripdata.zip
201503-citibike-tripdata.csv
201503-citibike-tripdata.zip
201504-citibike-tripdata.csv
201504-citibike-tripdata.zip
201505-citibike-tripdata.csv
201505-citibike-tripdata.zip
201506-citibike-tripdata.csv
201506-citibike-tripdata.zip
201507-citibike-tripdata.csv
201507-citibike-tripdata.zip
201508-citibike-tripdata.csv
201508-citibike-tripdata.zip
201509-citibike-tripdata.csv
201509-citibike-tripdata.zip
201510-citibike-tripdata.csv
201510-citibike-tripdata.zip
201511-citibike-tripdata.csv
201511-citibike-tripdata.zip
201512-citibike-tripdata.csv
201512-citibike-tripdata.zip
201601-citibike-tripdata.csv
201601-citibike-tripdata.zip
201602-citibike-tripdata.csv
201602-citibike-tripdata.zip
201603-citibike-tripdata.csv
201603-citibike-tripdata.zip
201604-citibike-tripdata.csv
201604-citibike-tripdata.zip
201605-citibike-tripdata.csv
201605-citibike-tripdata.zip
201606-citibike-tripdata.csv
201606-citibike-tripdata.zip
201607-citibike-tripdata.csv
201607-citibike-tripdata.zip
201608-citibike-tripdata.csv
201608-citibike-tripdata.zip
201609-citibike-tripdata.csv
201609-citibike-tripdata.zip
201610-citibike-tripdata.csv
201610-citibike-tripdata.zip
201611-citibike-tripdata.csv
201611-citibike-tripdata.zip
201612-citibike-tripdata.csv
201612-citibike-tripdata.zip
201701-citibike-tripdata.csv
201701-citibike-tripdata.csv.zip
201702-citibike-tripdata.csv
201702-citibike-tripdata.csv.zip
201703-citibike-tripdata.csv
201703-citibike-tripdata.csv.zip
201704-citibike-tripdata.csv
201704-citibike-tripdata.csv.zip
201705-citibike-tripdata.csv
201705-citibike-tripdata.csv.zip
201706-citibike-tripdata.csv
201706-citibike-tripdata.csv.zip
201707-citibike-tripdata.csv
201707-citibike-tripdata.csv.zip
201708-citibike-tripdata.csv
201708-citibike-tripdata.csv.zip
201709-citibike-tripdata.csv
201709-citibike-tripdata.csv.zip
201710-citibike-tripdata.csv
201710-citibike-tripdata.csv.zip
201711-citibike-tripdata.csv
201711-citibike-tripdata.csv.zip
201712-citibike-tripdata.csv
201712-citibike-tripdata.csv.zip
201801-citibike-tripdata.csv
201801-citibike-tripdata.csv.zip
201802-citibike-tripdata.csv
201802-citibike-tripdata.csv.zip
201803-citibike-tripdata.csv
201803-citibike-tripdata.csv.zip
201804-citibike-tripdata.csv
201804-citibike-tripdata.csv.zip
201805-citibike-tripdata.csv
201805-citibike-tripdata.csv.zip
201806-citibike-tripdata.csv
201806-citibike-tripdata.csv.zip
201807-citibike-tripdata.csv
201807-citibike-tripdata.csv.zip
201808-citibike-tripdata.csv
201808-citibike-tripdata.csv.zip
201809-citibike-tripdata.csv
201809-citibike-tripdata.csv.zip
201810-citibike-tripdata.csv
201810-citibike-tripdata.csv.zip
201811-citibike-tripdata.csv
201811-citibike-tripdata.csv.zip
201812-citibike-tripdata.csv
201812-citibike-tripdata.csv.zip
201901-citibike-tripdata.csv
201901-citibike-tripdata.csv.zip
201901-citibike-tripdata.csv.zip.1
201901-citibike-tripdata.csv.zip.2
201901-citibike-tripdata.csv.zip.3
201902-citibike-tripdata.csv
201902-citibike-tripdata.csv.zip
201902-citibike-tripdata.csv.zip.1
201902-citibike-tripdata.csv.zip.2
201902-citibike-tripdata.csv.zip.3
201903-citibike-tripdata.csv
201903-citibike-tripdata.csv.zip
201903-citibike-tripdata.csv.zip.1
201903-citibike-tripdata.csv.zip.2
201903-citibike-tripdata.csv.zip.3
201904-citibike-tripdata.csv
201904-citibike-tripdata.csv.zip
201904-citibike-tripdata.csv.zip.1
201904-citibike-tripdata.csv.zip.2
201904-citibike-tripdata.csv.zip.3
201905-citibike-tripdata.csv
201905-citibike-tripdata.csv.zip
201905-citibike-tripdata.csv.zip.1
201905-citibike-tripdata.csv.zip.2
201905-citibike-tripdata.csv.zip.3
201906-citibike-tripdata.csv
201906-citibike-tripdata.csv.zip
201906-citibike-tripdata.csv.zip.1
201906-citibike-tripdata.csv.zip.2
201906-citibike-tripdata.csv.zip.3
201907-citibike-tripdata.csv
201907-citibike-tripdata.csv.zip
201907-citibike-tripdata.csv.zip.1
201907-citibike-tripdata.csv.zip.2
201907-citibike-tripdata.csv.zip.3
201908-citibike-tripdata.csv.zip
201908-citibike-tripdata.csv.zip.1
201908-citibike-tripdata.csv.zip.2
201908-citibike-tripdata.csv.zip.3
201909-citibike-tripdata.csv
201909-citibike-tripdata.csv.zip
201909-citibike-tripdata.csv.zip.1
201909-citibike-tripdata.csv.zip.2
201910-citibike-tripdata.csv
201910-citibike-tripdata.csv.zip
201910-citibike-tripdata.csv.zip.1
201910-citibike-tripdata.csv.zip.2
201911-citibike-tripdata.csv
201911-citibike-tripdata.csv.zip
201911-citibike-tripdata.csv.zip.1
201911-citibike-tripdata.csv.zip.2
201912-citibike-tripdata.csv
201912-citibike-tripdata.csv.zip
201912-citibike-tripdata.csv.zip.1
201912-citibike-tripdata.csv.zip.2
__MACOSX
sample_data
urls_to_get.csv

In [ ]:
df = pd.read_csv("201903-citibike-tripdata.csv")
df

         tripduration                 starttime  ... birth year  gender
0                1463  2019-03-01 00:00:16.0970  ...       1989       1
1                 285  2019-03-01 00:00:32.3850  ...       1980       1
2                 686  2019-03-01 00:00:47.7970  ...       1987       1
3                 442  2019-03-01 00:01:01.2090  ...       1987       2
4                2913  2019-03-01 00:01:09.2810  ...       1991       1
...               ...                       ...  ...        ...     ...
1327955           351  2019-03-31 23:59:30.5850  ...       1985       1
1327956          1943  2019-03-31 23:59:55.3410  ...       1987       1
1327957           515  2019-03-31 23:59:50.1810  ...       1988       1
1327958           660  2019-03-31 23:59:56.6520  ...       1987       1
1327959           132  2019-03-31 23:59:58.0230  ...       1973       1

[1327960 rows x 15 columns]

Tokenizer_088f9146c201

+---+--------------------+
| id|            sentence|
+---+--------------------+
|  0|      Spark is great|
|  1|We are learning S...|
|  2|Spark is better t...|
+---+--------------------+

+---+------------------------------------+--------------------------------------------+
|id |sentence                            |words                                       |
+---+------------------------------------+--------------------------------------------+
|0  |Spark is great                      |[spark, is, great]                          |
|1  |We are learning Spark               |[we, are, learning, spark]                  |
|2  |Spark is better than hadoop no doubt|[spark, is, better, than, hadoop, no, doubt]|
+---+------------------------------------+--------------------------------------------+